apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.deployment.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mw-kube-agent.labels" . | nindent 4 }}
data:
  otel-config: |