{{- if .Values.features.enableRuntimePipelines }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    k8s-app: mw-app
  name: mw-role-update
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "update"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments"]
  verbs: ["get", "update"]
{{- end }}