apiVersion: v1
kind: Secret
metadata:
  name: middleware-secret
  namespace: {{ .Release.Namespace }}
  labels:
      {{- include "mw-kube-agent.labels" . | nindent 4 }}
type: Opaque

data:
  api-key: {{ or .Values.global.mw.apiKey .Values.mw.apiKey | b64enc | quote }}
