{{- if .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mw-auto-injector-tls
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - mw-auto-injector.{{ .Release.Namespace }}.svc
    - mw-auto-injector.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}
  issuerRef:
    kind: Issuer
    name: mw-auto-injector-selfsigned
  secretName: mw-auto-injector-tls
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: mw-auto-injector-selfsigned
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end }}
