
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: mw-autoinstrumentation
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- $skipPostUpgrade := and (not .Values.webhook.certManager.enabled) (.Release.IsUpgrade) }}
    {{- if $skipPostUpgrade }}
    "helm.sh/hook": post-install
    {{- else }}
    "helm.sh/hook": post-install,post-upgrade
    {{- end }}
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  exporter:
    endpoint: http://mw-service.{{ .Release.Namespace }}:9319
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"
  python:
    env:
      - name: MW_AGENT_SERVICE
        value: mw-service.{{ .Release.Namespace }}.svc.cluster.local
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://mw-service.{{ .Release.Namespace }}:9320
      - name: MW_API_KEY
        value: {{ or .Values.global.mw.apiKey "XXXXXX" | quote }}
      - name: OTEL_PROPAGATORS
        value: tracecontext,baggage,b3
  nodejs:
    env:
      - name: OTEL_NODE_DISABLED_INSTRUMENTATIONS
        value: fs,dns,net
      - name: OTEL_PROPAGATORS
        value: b3,tracecontext,baggage
  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://mw-service.{{ .Release.Namespace }}:9319
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      - name: OTEL_PROPAGATORS
        value: b3,tracecontext,baggage
  dotnet:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://mw-service.{{ .Release.Namespace }}:9320
      - name: OTEL_PROPAGATORS
        value: b3,tracecontext,baggage
  java:
    env:
      - name: MW_AGENT_SERVICE
        value: mw-service.{{ .Release.Namespace }}.svc.cluster.local
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://mw-service.{{ .Release.Namespace }}:9319
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: grpc
      - name: MW_API_KEY
        value: {{ or .Values.global.mw.apiKey "XXXXXX" | quote }}
      - name: OTEL_PROPAGATORS
        value: tracecontext,baggage,b3