apiVersion: v1
kind: Service
metadata:
  name: mw-auto-injector
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: mw-auto-injector