apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "mw-auto-injector.acme.com"
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/mw-auto-injector-tls
webhooks:
  - name: "mw-auto-injector.acme.com"
    namespaceSelector:
      matchExpressions:
      {{- if .Values.webhook.includedNamespaces }}
        - key: kubernetes.io/metadata.name
          operator: In
          values: {{ .Values.webhook.includedNamespaces | toJson }}
      {{- else }}
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values: {{ concat .Values.webhook.excludedNamespaces (list .Release.Namespace) .Values.webhook.userExcludedNamespaces | toJson  }}
      {{- end }}
    failurePolicy: Ignore
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["UPDATE"]
        resources: ["deployments","daemonsets", "statefulsets"]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ .Release.Namespace }}
        name: mw-auto-injector
        path: /mutate-resources
        port: 443
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5